# Generated by Django 2.2.24 on 2021-08-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210817_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
