# Generated by Django 2.2.24 on 2021-09-20 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210825_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('M', 'мужчина'), ('F', 'женщина'), ('MP', 'разнополый_гуманоид')], default=None, max_length=1, verbose_name='пол')),
                ('tagline', models.CharField(blank=True, max_length=128, verbose_name='теги')),
                ('description', models.TextField(blank=True, max_length=128, verbose_name='о себе')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
