# Generated by Django 2.2.24 on 2021-09-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210920_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='description',
            field=models.TextField(blank=True, max_length=256, verbose_name='о себе'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='gender',
            field=models.CharField(blank=True, choices=[(None, 'Выберите ваш пол'), ('M', 'мужчина'), ('F', 'женщина'), ('MP', 'разнополый_гуманоид')], default=None, max_length=1, null=True, verbose_name='пол'),
        ),
    ]
