# Generated by Django 2.2.24 on 2021-09-30 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0002_auto_20210924_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='products',
        ),
    ]
